languageCode: 'en-us'
title: 'Communications Hill'
copyright: 'commhill.org'
theme: 'ananke'

MetaDataFormat: 'yaml'
DefaultContentLanguage: 'en'
SectionPagesMenu: 'main'
Paginate: 10

sitemap:
  changefreq: 'monthly'
  priority: 0.5
  filename: 'sitemap.xml'

permalinks:
  posts: '/:year/:month/:day/:title/'

params:
  favicon: ''
  site_logo: ''
  github: 'https://github.com/typeobject/commhill-org'
  description: 'A neighborhood in San Jose, California.'
  background_color_class: 'bg-black'
  featured_image: '/images/trail-overlook-hero.jpg'
