languageCode: 'en-us'
title: 'Communications Hill'
theme: 'ananke'

MetaDataFormat: 'yaml'
DefaultContentLanguage: 'en'
SectionPagesMenu: 'main'
Paginate: 10

sitemap:
  changefreq: 'monthly'
  priority: 0.5
  filename: 'sitemap.xml'

permalinks:
  posts: '/:year/:month/:day/:title/'

params:
  favicon: ''
  site_logo: ''
  description: 'A neighborhood in San Jose, California.'
  background_color_class: 'bg-black'
  featured_image: '/images/trail-overlook-hero.jpg'
