baseURL: 'https://www.commhill.org/'
languageCode: 'en-us'
title: 'Communications Hill'
theme: 'ananke'

permalinks:
  posts: '/:year/:month/:day/:title/'

deployment:
  targets:
    - name: 'azuredeployment'
      URL: 'azblob://$web'
  matchers:
    - pattern: '^.+\.(html|xml|json)$'
      gzip: 'true'
