baseURL: 'https://www.commhill.org/'
languageCode: 'en-us'
title: 'Communications Hill'
theme: 'ananke'

googleAnalytics: 'UA-132850368-1'
enableRobotsTXT: true

sitemap:
  changefreq: 'monthly'
  priority: 0.5
  filename: 'sitemap.xml'

permalinks:
  posts: '/:year/:month/:day/:title/'

deployment:
  targets:
    - name: 'azuredeployment'
      URL: 'azblob://$web'
  matchers:
    - pattern: '^.+\.(html|xml|json)$'
      gzip: true
