baseURL = "http://commhill.org/"
languageCode = "en-us"
title = "Communications Hill"
theme = "ananke"

[deployment]

[[deployment.targets]]
name = "mydeployment"
URL = "azblob://$web"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
