baseURL: 'https://www.commhill.org/'

googleAnalytics: 'UA-132850368-1'
enableRobotsTXT: true

deployment:
  targets:
    - name: 'azuredeployment'
      URL: 'azblob://$web'
  matchers:
    - pattern: '^.+\.(html|xml|json)$'
      gzip: true
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: 'max-age=86400, no-transform, public'
      gzip: true
    - pattern: ^.+\.(png|jpg)$
      cacheControl: 'max-age=86400, no-transform, public'
      gzip: false
